services:
  - type: web
    name: cinepilot
    env: node
    plan: free
    buildCommand: npm install && (pip3 install cloudscraper beautifulsoup4 requests || pip install cloudscraper beautifulsoup4 requests || true)
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 7050
      - key: NODE_ENV
        value: production
      - key: TMDB_API_KEY
        value: caad8d4dace6ad77f0e22f5b746d5a20
